- name: Install maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: calling App-preq
  ansible.builtin.import_role:
    name: common
    tasks_from: app-preq.yml

- name: download maveen dependency package
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: install sql client
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: Load Schema
  ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', '{{component}}.{{env}}.DB_HOST', region='us-east-1') }} -u{{ lookup('amazon.aws.aws_ssm', 'rds.{{env}}.master_username', region='us-east-1') }} -p{{ lookup('amazon.aws.aws_ssm', 'rds.{{env}}.master_password', region='us-east-1') }} < /app/schema/{{component}}.sql

- name: calling systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yml