- name: setup app user
  ansible.builtin.user:
    name: roboshop

- name: cleanup old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: add application Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and Extract app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes
